# this script based off of https://github.com/tolbertam/mocha-appveyor-reporter/blob/master/appveyor.yml

environment:
  global:
    # we need to specify py3 because py2 is default (AREPL does not support py2)
    - PYTHON: "C:\\Python35-x64" # this version of python is pre-installed on appveyor
      PYTHON_VERSION: "3.5.x" # currently 3.5.3
      PYTHON_ARCH: "64"

install:
  # Get the latest stable version of Node.js
  - ps: Install-Product node ''
  - npm install

build: off

test_script:
  - npm test

cache:
  - node_modules -> package.json

notifications:
  - provider: Email
    to:
      - almenon214@gmail.com
    on_build_success: false